"""
PDF Risk Report Generator for FraudShield AI.
Generates a professional, downloadable PDF with prediction results,
SHAP explanations, feature impact chart, and similar transactions.
"""

import io
import tempfile
import datetime
import uuid
from pathlib import Path

import numpy as np
import pandas as pd
import plotly.graph_objects as go
from fpdf import FPDF


class RiskReportPDF(FPDF):
    """Custom PDF with FraudShield branding."""

    DARK = (15, 15, 30)
    ACCENT = (139, 92, 246)
    RED = (239, 68, 68)
    GREEN = (34, 197, 94)
    GRAY = (160, 160, 200)
    WHITE = (240, 240, 255)

    def header(self):
        self.set_font("Helvetica", "B", 22)
        self.set_text_color(*self.ACCENT)
        self.cell(0, 12, "FraudShield AI", new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "", 10)
        self.set_text_color(*self.GRAY)
        self.cell(0, 6, "Transaction Risk Assessment Report", new_x="LMARGIN", new_y="NEXT")
        # Divider
        self.set_draw_color(*self.ACCENT)
        self.set_line_width(0.5)
        self.line(10, self.get_y() + 2, 200, self.get_y() + 2)
        self.ln(8)

    def footer(self):
        self.set_y(-25)
        self.set_draw_color(*self.ACCENT)
        self.set_line_width(0.3)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(3)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(*self.GRAY)
        self.multi_cell(0, 4,
            "DISCLAIMER: This report is generated by an AI-based fraud detection system "
            "for informational purposes only. It should not be used as the sole basis for "
            "financial decisions. Always verify with your compliance team.",
            align="C",
        )
        self.cell(0, 4, f"Page {self.page_no()}/{{nb}}", align="C")

    def section_title(self, title):
        self.ln(4)
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(*self.ACCENT)
        self.cell(0, 8, title, new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(*self.ACCENT)
        self.set_line_width(0.2)
        self.line(10, self.get_y(), 80, self.get_y())
        self.ln(4)

    def key_value(self, key, value, value_color=None):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(*self.GRAY)
        self.cell(55, 6, key, new_x="RIGHT")
        self.set_font("Helvetica", "", 10)
        self.set_text_color(*(value_color or self.WHITE))
        self.cell(0, 6, str(value), new_x="LMARGIN", new_y="NEXT")


def _find_similar_transactions(input_values, dataset_df, feature_cols, n=5):
    """Find the n most similar transactions using Euclidean distance."""
    input_arr = np.array([input_values[f] for f in feature_cols]).reshape(1, -1)
    data_arr = dataset_df[feature_cols].values

    # Normalize for distance calc
    means = data_arr.mean(axis=0)
    stds = data_arr.std(axis=0)
    stds[stds == 0] = 1

    input_norm = (input_arr - means) / stds
    data_norm = (data_arr - means) / stds

    distances = np.sqrt(((data_norm - input_norm) ** 2).sum(axis=1))
    closest_idx = distances.argsort()[:n]

    similar = dataset_df.iloc[closest_idx].copy()
    similar["distance"] = distances[closest_idx]
    return similar


def _create_shap_chart_image(feature_names, shap_values, top_n=5):
    """Create a SHAP bar chart and return it as PNG bytes."""
    contrib = pd.Series(shap_values, index=feature_names)
    top = contrib.abs().sort_values(ascending=False).head(top_n)
    top_contrib = contrib[top.index].sort_values()

    colors = ["#f87171" if v > 0 else "#34d399" for v in top_contrib.values]

    fig = go.Figure(go.Bar(
        x=top_contrib.values,
        y=top_contrib.index,
        orientation="h",
        marker_color=colors,
        text=[f"{v:+.4f}" for v in top_contrib.values],
        textposition="outside",
        textfont=dict(size=12),
    ))
    fig.update_layout(
        title="Feature Impact (SHAP Values)",
        xaxis_title="Impact on Prediction",
        template="plotly_white",
        height=300,
        width=550,
        margin=dict(l=100, r=60, t=50, b=40),
        font=dict(family="Helvetica", size=11),
    )

    img_bytes = fig.to_image(format="png", scale=2)
    return img_bytes


def generate_risk_report(
    prediction,
    confidence,
    model_name,
    feature_values,
    feature_cols,
    reasons,
    shap_values=None,
    per_model_votes=None,
    per_model_probs=None,
    similar_df=None,
):
    """
    Generate a PDF risk report and return it as bytes.

    Parameters
    ----------
    prediction : int (0 or 1)
    confidence : float (e.g. 0.95)
    model_name : str
    feature_values : dict {feature_name: value}
    feature_cols : list of str
    reasons : list of str (plain-English explanations)
    shap_values : array-like, optional
    per_model_votes : dict {model_name: 0 or 1}, optional
    per_model_probs : dict {model_name: array}, optional
    similar_df : pd.DataFrame, optional

    Returns
    -------
    bytes : PDF file content
    """
    pdf = RiskReportPDF()
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=30)
    pdf.add_page()

    report_id = str(uuid.uuid4())[:8].upper()
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # ── 1. Report metadata ──
    pdf.section_title("Report Information")
    pdf.key_value("Report ID:", f"FR-{report_id}")
    pdf.key_value("Generated:", timestamp)
    pdf.key_value("Model Used:", model_name)

    # ── 2. Prediction Summary ──
    pdf.section_title("Prediction Summary")

    if prediction == 1:
        verdict = "FRAUDULENT TRANSACTION"
        verdict_color = RiskReportPDF.RED
        risk_level = "HIGH RISK"
        recommendation = "RECOMMEND BLOCKING"
    else:
        verdict = "LEGITIMATE TRANSACTION"
        verdict_color = RiskReportPDF.GREEN
        risk_level = "LOW RISK"
        recommendation = "APPROVE"

    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(*verdict_color)
    pdf.cell(0, 10, verdict, new_x="LMARGIN", new_y="NEXT", align="C")

    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(*RiskReportPDF.WHITE)
    conf_str = f"{confidence * 100:.1f}%" if confidence is not None else "N/A"
    pdf.cell(0, 7, f"Confidence: {conf_str}", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.cell(0, 7, f"Risk Level: {risk_level}  |  Action: {recommendation}",
             new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(4)

    # ── 3. Per-model votes (ensemble) ──
    if per_model_votes:
        pdf.section_title("Per-Model Votes (Ensemble)")

        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*RiskReportPDF.ACCENT)
        pdf.cell(55, 7, "Model", border="B")
        pdf.cell(30, 7, "Verdict", border="B")
        pdf.cell(35, 7, "Fraud Prob", border="B")
        pdf.cell(35, 7, "Legit Prob", border="B", new_x="LMARGIN", new_y="NEXT")

        pdf.set_font("Helvetica", "", 9)
        for name, vote in per_model_votes.items():
            color = RiskReportPDF.RED if vote == 1 else RiskReportPDF.GREEN
            pdf.set_text_color(*RiskReportPDF.WHITE)
            pdf.cell(55, 6, name)
            pdf.set_text_color(*color)
            pdf.cell(30, 6, "FRAUD" if vote == 1 else "SAFE")
            pdf.set_text_color(*RiskReportPDF.WHITE)
            if per_model_probs and name in per_model_probs:
                p = per_model_probs[name]
                pdf.cell(35, 6, f"{p[1]*100:.1f}%")
                pdf.cell(35, 6, f"{p[0]*100:.1f}%", new_x="LMARGIN", new_y="NEXT")
            else:
                pdf.cell(35, 6, "N/A")
                pdf.cell(35, 6, "N/A", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)

    # ── 4. Explanations ──
    pdf.section_title("Why This Decision?")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*RiskReportPDF.WHITE)

    for i, reason in enumerate(reasons[:5], 1):
        # Strip markdown bold markers for PDF
        clean = reason.replace("**", "").replace("⬆️", "[UP]").replace("⬇️", "[DOWN]")
        clean = clean.replace("💰", "[AMOUNT]").replace("🕐", "[TIME]")
        clean = clean.replace("🔬", "[PATTERN]").replace("📊", "[METRIC]")
        pdf.multi_cell(0, 5, f"{i}. {clean}")
        pdf.ln(1)

    # ── 5. SHAP chart ──
    if shap_values is not None:
        pdf.section_title("Feature Impact Chart")
        try:
            img_bytes = _create_shap_chart_image(feature_cols, shap_values)
            with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
                tmp.write(img_bytes)
                tmp_path = tmp.name
            pdf.image(tmp_path, x=25, w=160)
            pdf.ln(5)
            Path(tmp_path).unlink(missing_ok=True)
        except Exception:
            pdf.set_font("Helvetica", "I", 9)
            pdf.set_text_color(*RiskReportPDF.GRAY)
            pdf.cell(0, 6, "(Chart generation unavailable)", new_x="LMARGIN", new_y="NEXT")

    # ── 6. Similar transactions ──
    if similar_df is not None and not similar_df.empty:
        pdf.section_title("Similar Historical Transactions")

        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(*RiskReportPDF.GRAY)
        pdf.cell(0, 5, "Top 5 most similar transactions from the dataset (by Euclidean distance):",
                 new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

        # Table header
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(*RiskReportPDF.ACCENT)
        pdf.cell(10, 6, "#", border="B")
        pdf.cell(30, 6, "Amount", border="B")
        pdf.cell(30, 6, "Time", border="B")
        pdf.cell(30, 6, "Actual Label", border="B")
        pdf.cell(30, 6, "Distance", border="B")
        pdf.cell(50, 6, "Top Feature", border="B", new_x="LMARGIN", new_y="NEXT")

        pdf.set_font("Helvetica", "", 8)
        for i, (_, row) in enumerate(similar_df.head(5).iterrows(), 1):
            label = "FRAUD" if row.get("target", 0) == 1 else "LEGIT"
            color = RiskReportPDF.RED if label == "FRAUD" else RiskReportPDF.GREEN
            amount = row.get("Amount", 0)
            time_val = row.get("Time", 0)
            dist = row.get("distance", 0)

            # Find most notable V-feature
            v_cols = [c for c in similar_df.columns if c.startswith("V")]
            if v_cols:
                top_v = max(v_cols, key=lambda c: abs(row.get(c, 0)))
                top_feat = f"{top_v}={row[top_v]:.2f}"
            else:
                top_feat = "-"

            pdf.set_text_color(*RiskReportPDF.WHITE)
            pdf.cell(10, 5, str(i))
            pdf.cell(30, 5, f"${amount:.2f}")
            pdf.cell(30, 5, f"{time_val:.0f}s")
            pdf.set_text_color(*color)
            pdf.cell(30, 5, label)
            pdf.set_text_color(*RiskReportPDF.WHITE)
            pdf.cell(30, 5, f"{dist:.3f}")
            pdf.cell(50, 5, top_feat, new_x="LMARGIN", new_y="NEXT")

        # Summary
        n_fraud = int(similar_df.head(5)["target"].sum()) if "target" in similar_df.columns else 0
        pdf.ln(3)
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(*RiskReportPDF.GRAY)
        pdf.cell(0, 5,
                 f"Of the 5 most similar historical transactions, {n_fraud} were fraudulent.",
                 new_x="LMARGIN", new_y="NEXT")

    # ── 7. Key feature values ──
    pdf.section_title("Transaction Feature Values")
    pdf.set_font("Helvetica", "", 8)
    pdf.set_text_color(*RiskReportPDF.WHITE)

    # Show in 3-column layout
    items = list(feature_values.items())
    col_w = 60
    for i in range(0, len(items), 3):
        batch = items[i:i+3]
        for feat, val in batch:
            pdf.set_font("Helvetica", "B", 8)
            pdf.set_text_color(*RiskReportPDF.GRAY)
            pdf.cell(25, 5, feat)
            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(*RiskReportPDF.WHITE)
            pdf.cell(col_w - 25, 5, f"{val:.4f}")
        pdf.ln()

    # Return PDF as bytes
    return pdf.output()
